# Generated by Django 5.2.4 on 2025-07-09 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='user_profile.category'),
        ),
    ]
