# Generated by Django 5.2.4 on 2025-07-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_faculty_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
