# Generated by Django 5.2.4 on 2025-07-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
    ]
