# Generated by Django 5.2.4 on 2025-07-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_collage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collage',
            new_name='College',
        ),
    ]
