# Generated by Django 5.2.4 on 2025-07-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_rename_collage_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='image',
            field=models.ImageField(upload_to='college_images/'),
        ),
    ]
